[package]
name = "codex-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pretty_assertions = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
sentry = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
