[package]
name = "codex-process-hardening"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_process_hardening"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-utils-home-dir = { workspace = true }
libc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
