[package]
name = "cocode-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cocode-error = { path = "../error" }
cocode-protocol = { path = "../protocol" }
cocode-utils-common = { workspace = true }
hyper-sdk = { workspace = true }
dirs = "5"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
jsonc-parser = { version = "0.24", features = ["serde"] }
snafu.workspace = true
snafu-virtstack.workspace = true
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
