[package]
name = "cocode-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cocode-error = { path = "../error" }
cocode-protocol = { path = "../protocol" }
dirs = "5"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
snafu.workspace = true
snafu-virtstack.workspace = true
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
