[package]
name = "helios-utils-oss"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
helios-core = { workspace = true }
helios-lmstudio = { workspace = true }
helios-ollama = { workspace = true }
