[package]
name = "cocode-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
humantime-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true }

[lints]
workspace = true
