[package]
name = "helios-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "helios_arg0"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
helios-apply-patch = { workspace = true }
helios-linux-sandbox = { workspace = true }
helios-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
