[package]
name = "codex-api"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"
bytes = "1"
codex-client = { path = "../codex-client" }
codex-protocol = { path = "../protocol" }
futures = "0.3"
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
tokio-stream = "0.1"
tracing = "0.1"
eventsource-stream = { workspace = true }
reqwest = { version = "0.12", features = ["json", "stream"] }
once_cell = "1"
regex-lite = { workspace = true }
tokio-util = { version = "0.7", features = ["codec"] }

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }
tokio-test = "0.4"

[lints]
workspace = true
