[package]
name = "helios-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
helios-core = { workspace = true }
helios-protocol = { workspace = true }

[dev-dependencies]
helios-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
